version: "3.8"

services:

  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=fastapi_database

  backend:
    container_name: backend
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd app/ ;uvicorn main:app'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always